version: '3.8'

services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac
      POSTGRES_DB: prac
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/warghkhan/film-backend:latest
    restart: always
    environment:
      DATABASE_DRIVER: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: prac
      DB_PASSWORD: prac
      DB_NAME: prac
      LOGGER_TYPE: json
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/warghkhan/film-frontend:latest
    volumes:
      - frontend_build:/build
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ghcr.io/warghkhan/film-nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:
  frontend_build:

networks:
  app-network:
    driver: bridge